<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Simple.API" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sicoob.Cobranca\Sicoob.Cobranca.csproj" />
    <ProjectReference Include="..\Sicoob.Conta\Sicoob.Conta.csproj" />
    <ProjectReference Include="..\Sicoob.PIX\Sicoob.PIX.csproj" />
  </ItemGroup>

</Project>
